[package]
name = "exec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
authors.workspace = true
repository.workspace = true

[dependencies]
base          = { workspace = true }
tokio         = { workspace = true }
tokio-util    = { workspace = true }
futures       = { workspace = true }
async-trait   = { workspace = true }
reqwest       = { workspace = true }
tracing       = { workspace = true }
which         = { workspace = true }
url           = { workspace = true }

[dev-dependencies]
tempfile      = { workspace = true }
